services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mypassword"
  data-generator:
    platform: linux/amd64
    build: data_generator/
    command:
      - "db"
